id: I8586E578
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:56:37+00:00'
last_modified: '2022-06-08T01:20:35.789297+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16751
  title: ཁྲོ་བོ་སྐུ་གསུང་ཐུགས་ཀྱི་སྒྲུབ་ཐབས་ཀྱི་འགྲེལ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B861:
      image_group_id: I8LS16773
      title: ''
      total_pages: 116
      order: 1
      base_file: B861.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
