id: P004474
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16751
  title: ཁྲོ་བོ་སྐུ་གསུང་ཐུགས་ཀྱི་སྒྲུབ་ཐབས་ཀྱི་འགྲེལ་བ།
  author: ''
  volumes:
    2bafd2dcc3f64cd0bab345274f8ef9cc:
      image_group_id: I8LS16773
      title: ''
      volume_number: 1
      total_pages: 116
      base_file: v001.txt
