id: P004474
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 11:25:00.407044
source_metadata:
  id: bdr:W8LS16751
  title: ཁྲོ་བོ་སྐུ་གསུང་ཐུགས་ཀྱི་སྒྲུབ་ཐབས་ཀྱི་འགྲེལ་བ།
  author: ''
  volumes:
    2bafd2dcc3f64cd0bab345274f8ef9cc:
      image_group_id: I8LS16773
      title: ''
      volume_number: 1
      total_pages: 116
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
